# Generated by Django 4.2.1 on 2023-05-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article",
            new_name="Post",
        ),
    ]
