# Generated by Django 4.2.1 on 2023-05-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0006_follow_favorite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="likes",
            new_name="favorites",
        ),
    ]
