# Generated by Django 4.2.1 on 2023-05-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0007_rename_likes_post_favorites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="Followed_user",
            new_name="followed_user",
        ),
        migrations.RenameField(
            model_name="follow",
            old_name="Follower_user",
            new_name="follower_user",
        ),
        migrations.AddField(
            model_name="comment",
            name="floor",
            field=models.IntegerField(default=0),
        ),
    ]
