# Generated by Django 4.2.1 on 2023-05-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0008_rename_followed_user_follow_followed_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="floor",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="follow",
            name="followed_user",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="follow",
            name="follower_user",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
