# Generated by Django 4.2.1 on 2023-05-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0009_alter_comment_floor_alter_follow_followed_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="floor",
            new_name="now_floor",
        ),
        migrations.AddField(
            model_name="comment",
            name="body",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="to_floor",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
