# Generated by Django 4.2.1 on 2023-05-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0010_rename_floor_comment_now_floor_comment_body_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="comment_sum",
            new_name="comments",
        ),
    ]
