# Generated by Django 4.2.1 on 2023-05-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0011_rename_comment_sum_post_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="body",
        ),
    ]
