# Generated by Django 4.2.1 on 2023-05-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0014_alter_follow_follower_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bbs.post"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bbs.user"
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bbs.post"
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bbs.user"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bbs.user"
            ),
        ),
    ]
